#!/usr/bin/env python3
"""
🔥 CRAX KEYWORD GENERATOR BOT 🔥
Advanced Professional Telegram Bot for Keyword Generation
Developer: @CRAXOP
Version: 2.0 Pro
"""

import requests
import json
import re
import time
import logging
import asyncio
import aiohttp
import random
import string
from datetime import datetime, timedelta
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup, Document
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes, CallbackQueryHandler
from io import StringIO
import tempfile
import os
import os

# ═══════════════════════════════════════════════════════════════════════════════
# 🔧 BOT CONFIGURATION - REPLACE WITH YOUR ACTUAL VALUES
# ═══════════════════════════════════════════════════════════════════════════════

BOT_TOKEN = "7971091050:AAFL99d8DHOO_3Fzgq4FK76l1WsMoO8k51Q"  # Get from @BotFather
ADMIN_ID = 7141695869  # Your Telegram User ID from @userinfobot

# ═══════════════════════════════════════════════════════════════════════════════
# 🔐 SUBSCRIPTION MANAGEMENT SYSTEM
# ═══════════════════════════════════════════════════════════════════════════════

ACCESS_FILE = "accessusers.txt"
KEYS_FILE = "generated_keys.json"

class SubscriptionManager:
    """Advanced subscription management system"""
    
    def __init__(self):
        self.ensure_files_exist()
    
    def ensure_files_exist(self):
        """Ensure required files exist"""
        if not os.path.exists(ACCESS_FILE):
            with open(ACCESS_FILE, 'w', encoding='utf-8') as f:
                f.write("# CRAX KEYWORD GENERATOR - ACCESS USERS\n")
                f.write("# Format: telegram_id - username - expiry_date\n")
                f.write("# Generated by CRAX Bot System\n\n")
        
        if not os.path.exists(KEYS_FILE):
            with open(KEYS_FILE, 'w', encoding='utf-8') as f:
                json.dump({}, f)
    
    def generate_key(self, days: int) -> str:
        """Generate a unique access key"""
        # Load existing keys
        with open(KEYS_FILE, 'r', encoding='utf-8') as f:
            keys_data = json.load(f)
        
        # Generate unique key
        while True:
            serial = ''.join(random.choices(string.digits, k=6))
            key = f"CRAX-KEYWORD-{serial}"
            if key not in keys_data:
                break
        
        # Save key with expiry info
        keys_data[key] = {
            "days": days,
            "generated_date": datetime.now().isoformat(),
            "redeemed": False,
            "redeemed_by": None,
            "redeemed_date": None
        }
        
        with open(KEYS_FILE, 'w', encoding='utf-8') as f:
            json.dump(keys_data, f, indent=2)
        
        return key
    
    def redeem_key(self, key: str, user_id: int, username: str) -> dict:
        """Redeem an access key"""
        with open(KEYS_FILE, 'r', encoding='utf-8') as f:
            keys_data = json.load(f)
        
        if key not in keys_data:
            return {"success": False, "message": "Invalid key"}
        
        if keys_data[key]["redeemed"]:
            return {"success": False, "message": "Key already redeemed"}
        
        # Check if user already has access
        if self.has_access(user_id):
            return {"success": False, "message": "User already has active subscription"}
        
        # Redeem key
        days = keys_data[key]["days"]
        expiry_date = datetime.now() + timedelta(days=days)
        
        keys_data[key]["redeemed"] = True
        keys_data[key]["redeemed_by"] = user_id
        keys_data[key]["redeemed_date"] = datetime.now().isoformat()
        
        # Save updated keys
        with open(KEYS_FILE, 'w', encoding='utf-8') as f:
            json.dump(keys_data, f, indent=2)
        
        # Add user to access file
        self.add_user_access(user_id, username, expiry_date)
        
        return {
            "success": True, 
            "message": f"Key redeemed successfully! Access granted for {days} days",
            "expiry_date": expiry_date.strftime("%Y-%m-%d %H:%M:%S")
        }
    
    def add_user_access(self, user_id: int, username: str, expiry_date: datetime):
        """Add user to access file"""
        with open(ACCESS_FILE, 'a', encoding='utf-8') as f:
            f.write(f"{user_id} - {username} - {expiry_date.strftime('%Y-%m-%d %H:%M:%S')}\n")
    
    def has_access(self, user_id: int) -> bool:
        """Check if user has active access"""
        if user_id == ADMIN_ID:
            return True
        
        try:
            with open(ACCESS_FILE, 'r', encoding='utf-8') as f:
                lines = f.readlines()
            
            current_time = datetime.now()
            
            for line in lines:
                if line.startswith('#') or not line.strip():
                    continue
                
                parts = line.strip().split(' - ')
                if len(parts) >= 3:
                    stored_user_id = int(parts[0])
                    expiry_str = parts[2]
                    expiry_date = datetime.strptime(expiry_str, '%Y-%m-%d %H:%M:%S')
                    
                    if stored_user_id == user_id and current_time < expiry_date:
                        return True
            
            return False
        except:
            return False
    
    def get_user_expiry(self, user_id: int) -> datetime:
        """Get user's subscription expiry date"""
        try:
            with open(ACCESS_FILE, 'r', encoding='utf-8') as f:
                lines = f.readlines()
            
            for line in lines:
                if line.startswith('#') or not line.strip():
                    continue
                
                parts = line.strip().split(' - ')
                if len(parts) >= 3:
                    stored_user_id = int(parts[0])
                    expiry_str = parts[2]
                    
                    if stored_user_id == user_id:
                        return datetime.strptime(expiry_str, '%Y-%m-%d %H:%M:%S')
            
            return None
        except:
            return None
    
    def get_all_users(self) -> list:
        """Get all users with access"""
        users = []
        try:
            with open(ACCESS_FILE, 'r', encoding='utf-8') as f:
                lines = f.readlines()
            
            for line in lines:
                if line.startswith('#') or not line.strip():
                    continue
                
                parts = line.strip().split(' - ')
                if len(parts) >= 3:
                    user_id = int(parts[0])
                    username = parts[1]
                    expiry_str = parts[2]
                    expiry_date = datetime.strptime(expiry_str, '%Y-%m-%d %H:%M:%S')
                    
                    users.append({
                        "user_id": user_id,
                        "username": username,
                        "expiry_date": expiry_date,
                        "active": datetime.now() < expiry_date
                    })
            
            return users
        except:
            return []
    
    def cleanup_expired_users(self):
        """Remove expired users from access file"""
        try:
            users = self.get_all_users()
            active_users = [u for u in users if u["active"]]
            
            with open(ACCESS_FILE, 'w', encoding='utf-8') as f:
                f.write("# CRAX KEYWORD GENERATOR - ACCESS USERS\n")
                f.write("# Format: telegram_id - username - expiry_date\n")
                f.write("# Generated by CRAX Bot System\n\n")
                
                for user in active_users:
                    f.write(f"{user['user_id']} - {user['username']} - {user['expiry_date'].strftime('%Y-%m-%d %H:%M:%S')}\n")
        except:
            pass

# Initialize subscription manager
subscription_manager = SubscriptionManager()

# ═══════════════════════════════════════════════════════════════════════════════
# 🎯 ADVANCED LOGGING CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO,
    handlers=[
        logging.FileHandler('crax_bot.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

# ═══════════════════════════════════════════════════════════════════════════════
# 🚀 ADVANCED KEYWORD GENERATION ENGINE
# ═══════════════════════════════════════════════════════════════════════════════

class KeywordGenerator:
    """Advanced Keyword Generation System"""
    
    def __init__(self):
        self.session = None
        self.api_endpoints = [
            "https://api.datamuse.com/words",
            "https://api.wordnik.com/v4/words.json/search",
        ]
    
    async def initialize_session(self):
        """Initialize async HTTP session"""
        if not self.session:
            self.session = aiohttp.ClientSession()
    
    async def close_session(self):
        """Close HTTP session"""
        if self.session:
            await self.session.close()
    
    async def generate_semantic_keywords(self, topic: str, count: int = 50) -> list:
        """Generate semantically related keywords using multiple APIs"""
        await self.initialize_session()
        keywords = set()
        
        try:
            # Method 1: Datamuse API for related words
            datamuse_keywords = await self._fetch_datamuse_keywords(topic, count)
            keywords.update(datamuse_keywords)
            
            # Method 2: Generate contextual variations
            contextual_keywords = self._generate_contextual_keywords(topic, count)
            keywords.update(contextual_keywords)
            
            # Method 3: Generate semantic variations
            semantic_keywords = self._generate_semantic_variations(topic, count)
            keywords.update(semantic_keywords)
            
            # Method 5: Generate additional variations for large counts
            if count > 100:
                additional_keywords = self._generate_additional_variations(topic, count)
                keywords.update(additional_keywords)
            
            # Method 6: Generate compound keywords for very large counts
            if count > 300:
                compound_keywords = self._generate_compound_keywords(topic, count)
                keywords.update(compound_keywords)
            
        except Exception as e:
            logger.error(f"Error generating keywords: {e}")
            # Fallback to basic keyword generation
            keywords = self._generate_fallback_keywords(topic)
        
        # Clean and filter keywords
        filtered_keywords = self._filter_and_clean_keywords(list(keywords), topic)
        
        # Return requested number of keywords
        return filtered_keywords[:count]
    
    async def _fetch_datamuse_keywords(self, topic: str, count: int = 50) -> list:
        """Fetch related words from Datamuse API"""
        keywords = []
        
        try:
            # Get words that mean the same as the topic
            url = f"https://api.datamuse.com/words?ml={topic}&max={min(50, count//2)}"
            async with self.session.get(url, timeout=10) as response:
                if response.status == 200:
                    data = await response.json()
                    keywords.extend([item['word'] for item in data])
            
            # Get words that are triggered by the topic
            url = f"https://api.datamuse.com/words?rel_trg={topic}&max={min(30, count//3)}"
            async with self.session.get(url, timeout=10) as response:
                if response.status == 200:
                    data = await response.json()
                    keywords.extend([item['word'] for item in data])
            
            # Get words that rhyme with the topic
            url = f"https://api.datamuse.com/words?rel_rhy={topic}&max={min(20, count//4)}"
            async with self.session.get(url, timeout=10) as response:
                if response.status == 200:
                    data = await response.json()
                    keywords.extend([item['word'] for item in data])
                    
        except Exception as e:
            logger.error(f"Datamuse API error: {e}")
        
        return keywords
    
    def _generate_contextual_keywords(self, topic: str, count: int = 50) -> list:
        """Generate contextual keyword variations"""
        words = topic.lower().split()
        keywords = []
        
        # Common prefixes and suffixes for business/tech keywords
        prefixes = ['best', 'top', 'free', 'cheap', 'premium', 'professional', 'advanced', 'ultimate', 'quality', 'reliable', 'trusted', 'leading', 'expert', 'certified']
        suffixes = ['service', 'solution', 'tool', 'software', 'app', 'platform', 'system', 'guide', 'tips', 'tricks', 'methods', 'strategies', 'techniques', 'approach']
        
        # Generate combinations
        for word in words:
            # Add prefixes
            for prefix in prefixes:
                keywords.append(f"{prefix} {word}")
                keywords.append(f"{prefix} {topic}")
            
            # Add suffixes
            for suffix in suffixes:
                keywords.append(f"{word} {suffix}")
                keywords.append(f"{topic} {suffix}")
        
        # Add question-based keywords
        question_starters = ['how to', 'what is', 'why', 'when', 'where to find', 'how do', 'what are', 'where can', 'which', 'who uses']
        for starter in question_starters:
            keywords.append(f"{starter} {topic}")
        
        return keywords
    
    def _generate_semantic_variations(self, topic: str, count: int = 50) -> list:
        """Generate semantic variations and related terms"""
        keywords = []
        
        # Industry-specific mappings
        semantic_map = {
            'credit card': ['payment', 'finance', 'banking', 'money', 'transaction', 'purchase', 'debt', 'loan'],
            'marketing': ['advertising', 'promotion', 'branding', 'campaign', 'digital', 'social media'],
            'technology': ['software', 'hardware', 'innovation', 'digital', 'tech', 'IT', 'computer'],
            'health': ['medical', 'wellness', 'fitness', 'healthcare', 'medicine', 'treatment'],
            'education': ['learning', 'training', 'course', 'school', 'university', 'knowledge'],
            'business': ['company', 'corporate', 'enterprise', 'startup', 'entrepreneur', 'commerce']
        }
        
        # Find related terms
        topic_lower = topic.lower()
        for key, values in semantic_map.items():
            if any(word in topic_lower for word in key.split()):
                keywords.extend(values)
                # Create combinations
                for value in values:
                    keywords.append(f"{topic} {value}")
                    keywords.append(f"{value} {topic}")
        
        return keywords
    
    def _generate_industry_keywords(self, topic: str, count: int = 50) -> list:
        """Generate industry-specific keywords"""
        keywords = []
        
        # Action words
        actions = ['buy', 'sell', 'get', 'find', 'compare', 'review', 'learn', 'discover', 'choose', 'select', 'purchase', 'obtain', 'acquire', 'search']
        
        # Modifiers
        modifiers = ['online', 'digital', 'mobile', 'instant', 'quick', 'easy', 'secure', 'reliable', 'affordable', 'cheap', 'expensive', 'premium', 'quality', 'fast']
        
        # Generate combinations
        for action in actions:
            keywords.append(f"{action} {topic}")
        
        for modifier in modifiers:
            keywords.append(f"{modifier} {topic}")
        
        return keywords
    
    def _generate_additional_variations(self, topic: str, count: int) -> list:
        """Generate additional keyword variations for large counts"""
        keywords = []
        words = topic.lower().split()
        
        # Extended modifiers for large counts
        extended_modifiers = [
            'new', 'old', 'modern', 'traditional', 'innovative', 'creative', 'unique', 'special',
            'custom', 'personalized', 'automated', 'manual', 'smart', 'intelligent', 'powerful',
            'simple', 'complex', 'basic', 'advanced', 'expert', 'beginner', 'intermediate',
            'local', 'global', 'international', 'domestic', 'commercial', 'business', 'personal',
            'private', 'public', 'exclusive', 'popular', 'trending', 'latest', 'updated'
        ]
        
        # Time-based keywords
        time_modifiers = [
            '2024', '2025', 'today', 'now', 'current', 'recent', 'latest', 'new',
            'daily', 'weekly', 'monthly', 'yearly', 'seasonal', 'temporary', 'permanent'
        ]
        
        # Generate combinations
        for word in words:
            for modifier in extended_modifiers:
                keywords.append(f"{modifier} {word}")
                keywords.append(f"{modifier} {topic}")
            
            for time_mod in time_modifiers:
                keywords.append(f"{word} {time_mod}")
                keywords.append(f"{topic} {time_mod}")
        
        return keywords
    
    def _generate_compound_keywords(self, topic: str, count: int) -> list:
        """Generate compound keywords for very large counts"""
        keywords = []
        words = topic.lower().split()
        
        # Business terms
        business_terms = [
            'strategy', 'management', 'consulting', 'analysis', 'optimization', 'automation',
            'integration', 'implementation', 'development', 'improvement', 'enhancement',
            'transformation', 'innovation', 'solution', 'framework', 'methodology'
        ]
        
        # Technical terms
        tech_terms = [
            'api', 'software', 'application', 'platform', 'system', 'technology', 'digital',
            'cloud', 'mobile', 'web', 'online', 'virtual', 'artificial', 'machine', 'data'
        ]
        
        # Industry terms
        industry_terms = [
            'market', 'industry', 'sector', 'business', 'enterprise', 'corporate', 'startup',
            'company', 'organization', 'agency', 'firm', 'service', 'provider', 'vendor'
        ]
        
        # Generate compound combinations
        all_terms = business_terms + tech_terms + industry_terms
        
        for word in words:
            for term in all_terms:
                keywords.append(f"{word} {term}")
                keywords.append(f"{term} {word}")
                keywords.append(f"{topic} {term}")
                keywords.append(f"{term} {topic}")
        
        return keywords
    
    def _generate_fallback_keywords(self, topic: str) -> set:
        """Fallback keyword generation when APIs fail"""
        keywords = set()
        words = topic.lower().split()
        
        # Basic variations
        for word in words:
            keywords.add(word)
            keywords.add(f"{word}s")  # Plural
            keywords.add(f"{word}ing")  # Gerund
            keywords.add(f"{word}ed")  # Past tense
        
        # Common combinations
        common_terms = ['best', 'top', 'free', 'online', 'guide', 'tips', 'how to', 'review']
        for term in common_terms:
            keywords.add(f"{term} {topic}")
        
        return keywords
    
    def _filter_and_clean_keywords(self, keywords: list, original_topic: str) -> list:
        """Filter and clean generated keywords"""
        cleaned = []
        seen = set()
        
        for keyword in keywords:
            # Clean the keyword
            clean_keyword = re.sub(r'[^\w\s-]', '', keyword.lower().strip())
            
            # Skip if empty, too short, or already seen
            if not clean_keyword or len(clean_keyword) < 2 or clean_keyword in seen:
                continue
            
            # Skip if it's just the original topic
            if clean_keyword == original_topic.lower():
                continue
            
            seen.add(clean_keyword)
            cleaned.append(clean_keyword)
        
        # Sort by relevance (keywords containing original topic first)
        topic_words = set(original_topic.lower().split())
        
        def relevance_score(kw):
            kw_words = set(kw.split())
            intersection = len(topic_words.intersection(kw_words))
            return intersection
        
        cleaned.sort(key=relevance_score, reverse=True)
        return cleaned

# ═══════════════════════════════════════════════════════════════════════════════
# 🎨 TELEGRAM BOT HANDLERS
# ═══════════════════════════════════════════════════════════════════════════════

# Initialize keyword generator
keyword_gen = KeywordGenerator()

async def start_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """🏠 Professional welcome message"""
    user = update.effective_user
    username = f"@{user.username}" if user.username else user.first_name
    
    welcome_message = f"""
🔥 **WELCOME TO CRAX KEYWORD GENERATOR** 🔥

Hello {username}! 👋

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🚀 **PROFESSIONAL KEYWORD GENERATOR TOOL**

✨ Generate **HIGH-QUALITY** keywords for any topic
🎯 **ADVANCED** semantic analysis
⚡ **INSTANT** results in TXT format
🔥 **PROFESSIONAL** grade output

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎪 **Ready to see the MAGIC?**
Type `/cmd` to explore all features!

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
🏷️ **Version:** 2.0 Pro
    """
    
    keyboard = [
        [InlineKeyboardButton("🎯 VIEW COMMANDS", callback_data="show_commands")],
        [InlineKeyboardButton("💻 CONTACT DEVELOPER", url="https://t.me/CRAXOP")]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)
    
    await update.message.reply_text(
        welcome_message,
        parse_mode='Markdown',
        reply_markup=reply_markup
    )

async def cmd_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """📋 Show all available commands"""
    
    cmd_message = f"""
🎯 **CRAX KEYWORD GENERATOR - COMMAND CENTER**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔥 **AVAILABLE COMMANDS:**

🏠 `/start` - **HOME PAGE**
   └ Return to main welcome screen

🎯 `/keywords <topic> <quantity>` - **GENERATE KEYWORDS**
   └ Example: `/keywords credit card 500`
   └ Get HQ keyword Generations
   └ ⚡ UNLIMITED KEYWORDS! ♾️

📋 `/cmd` - **COMMAND CENTER**
   └ View this command list

📊 `/stats` - **BOT STATISTICS** (Admin Only)
   └ View bot performance metrics

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💡 **HOW TO USE:**
1️⃣ Type `/keywords` followed by your topic
2️⃣ Wait for processing ⚡
3️⃣ Receive professional TXT file 📄
4️⃣ Download and use for your projects! 🚀

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔥 **EXAMPLE USAGE:**
• `/keywords united states`
• `/keywords cryptocurrency`
• `/keywords database`
• `/keywords b@nks`

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
⚡ **Powered by CraxOP**
    """
    
    keyboard = [
        [InlineKeyboardButton("🔥 TRY NOW", callback_data="try_keywords")],
        [InlineKeyboardButton("🏠 HOME", callback_data="go_home")]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)
    
    await update.message.reply_text(
        cmd_message,
        parse_mode='Markdown',
        reply_markup=reply_markup
    )

async def keywords_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """🎯 Generate keywords for given topic with custom count"""
    user = update.effective_user
    
    # Check if user has access
    if not subscription_manager.has_access(user.id):
        await update.message.reply_text(
            f"""
🔒 **NO ACTIVE SUBSCRIPTION**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

❌ **ACCESS DENIED**

You need an active subscription to use this bot.

🔑 **GET ACCESS:**
Contact @CRAXOP to purchase a subscription key

💡 **HOW TO REDEEM:**
Once you have a key, use: `/redeem YOUR-KEY`

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
            """,
            parse_mode='Markdown'
        )
        return
    
    # Extract topic from command
    if not context.args:
        error_message = f"""
❌ **INVALID COMMAND FORMAT**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔥 **CORRECT USAGE:**
`/keywords <topic> <count>`

💡 **EXAMPLES:**
• `/keywords credit card 500`
• `/keywords digital marketing 1000`
• `/keywords web development 750`

📊 **COUNT LIMITS:**
• Minimum: 10 keywords
• Maximum: UNLIMITED ♾️
• Quantity REQUIRED (no default)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
        """
        await update.message.reply_text(error_message, parse_mode='Markdown')
        return
    
    # Parse arguments
    args = context.args
    
    # Check if last argument is a number (REQUIRED)
    if len(args) >= 2 and args[-1].isdigit():
        keyword_count = int(args[-1])
        topic = ' '.join(args[:-1]).strip()
    else:
        # No count specified - show error
        await update.message.reply_text(
            f"""
❌ **QUANTITY NOT SPECIFIED!**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔥 **CORRECT USAGE:**
`/keywords <topic> <quantity>`

💡 **EXAMPLES:**
• `/keywords credit card 100`
• `/keywords digital marketing 250`
• `/keywords web development 500`
• `/keywords cryptocurrency 1000`

⚡ **UNLIMITED POWER:**
• Minimum: 10 keywords
• Maximum: UNLIMITED ♾️
• You MUST specify the quantity!

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
            """,
            parse_mode='Markdown'
        )
        return
    
    # Validate minimum keyword count
    if keyword_count < 10:
        await update.message.reply_text(
            f"❌ **MINIMUM 10 KEYWORDS REQUIRED!**\n\nYou requested: {keyword_count}\nMinimum allowed: 10\n\n👨‍💻 **Developer:** @CRAXOP",
            parse_mode='Markdown'
        )
        return
    
    if len(topic) < 2:
        await update.message.reply_text(
            "❌ **Topic too short!** Please provide a meaningful topic.\n\n👨‍💻 **Developer:** @CRAXOP",
            parse_mode='Markdown'
        )
        return
    
    # Send processing message
    processing_msg = await update.message.reply_text(
        f"""
🔥 **CRAX KEYWORD GENERATOR ACTIVATED!**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎯 **TOPIC:** `{topic}`
⚡ **STATUS:** Processing with All Over World...
🔄 **PROGRESS:** Analyzing semantic relationships...

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⏳ **Please wait while we generate professional keywords...**

👨‍💻 **Developer:** @CRAXOP
        """,
        parse_mode='Markdown'
    )
    
    try:
        # Generate keywords using advanced AI with custom count
        keywords = await keyword_gen.generate_semantic_keywords(topic, keyword_count)
        
        if not keywords:
            await processing_msg.edit_text(
                f"""
❌ **KEYWORD GENERATION FAILED**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎯 **TOPIC:** `{topic}`
⚠️ **ERROR:** Unable to generate keywords

💡 **SUGGESTIONS:**
• Try a different topic
• Use more specific terms
• Check your spelling

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
                """,
                parse_mode='Markdown'
            )
            return
        
        # Create professional TXT file
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"CRAX_Keywords_{topic.replace(' ', '_')}_{timestamp}.txt"
        
        # Generate professional file content
        file_content = f"""
║                           CRAX KEYWORD GENERATOR                           
                             PROFESSIONAL EDITION                               


 KEYWORD ANALYSIS REPORT :



 TARGET TOPIC: {topic.upper()}
 GENERATED ON: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
 TOTAL KEYWORDS: {len(keywords)}
 PROCESSING METHOD: Advanced Semantic Analysis
 Must Check Last Some Lines and Remove Unwanted Content




🔥 HIGH-QUALITY KEYWORDS:



"""
        
        # Add keywords with professional formatting
        for keyword in keywords:
            file_content += f"{keyword}\n"
        
        file_content += f"""



💡 Specially Made For:
• Cred!t C@rd Dumpers
• Combo Dumpers  
• SEO Releated Workers
• Use For Any Purpose

🔥 KEYWORD CATEGORIES INCLUDED:
• Semantic variations
• Enhanced For Dumpers
• Industry-specific terms
• Best And Working




 
                     🚀 POWERED BY CRAX TECHNOLOGIES 🚀                       
                          👨‍💻 Developer: @CRAXOP                              
                       ⚡ Advanced Keyword Generation                       

        """
        
        # Create temporary file
        with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False, encoding='utf-8') as temp_file:
            temp_file.write(file_content)
            temp_file_path = temp_file.name
        
        # Send success message with file
        success_message = f"""
✅ **KEYWORD GENERATION COMPLETED!**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎯 **TOPIC:** `{topic}`
🔢 **KEYWORDS GENERATED:** {len(keywords)}
📄 **FILE FORMAT:** Professional TXT
⚡ **PROCESSING TIME:** {datetime.now().strftime("%H:%M:%S")}

🔥 **FEATURES INCLUDED:**
✨ Crax-Powered semantic analysis
🎯 Industry-specific variations
📊 Professional formatting
⚡ Ready-to-use keywords

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
🚀 **Thank you for using CRAX Keyword Generator!**
        """
        
        # Send file
        with open(temp_file_path, 'rb') as file:
            await update.message.reply_document(
                document=file,
                filename=filename,
                caption=success_message,
                parse_mode='Markdown'
            )
        
        # Clean up temporary file
        os.unlink(temp_file_path)
        
        # Delete processing message
        await processing_msg.delete()
        
        # Log successful generation
        logger.info(f"Keywords generated for user {user.id} ({user.username}): {topic} - {len(keywords)} keywords")
        
    except Exception as e:
        logger.error(f"Error generating keywords for {topic}: {e}")
        await processing_msg.edit_text(
            f"""
❌ **SYSTEM ERROR OCCURRED**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎯 **TOPIC:** `{topic}`
⚠️ **ERROR:** Technical issue during processing

💡 **PLEASE TRY:**
• Wait a moment and retry
• Use a different topic
• Contact support if issue persists

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
            """,
            parse_mode='Markdown'
        )

async def admin_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """🔐 Admin Panel (Admin only)"""
    if update.effective_user.id != ADMIN_ID:
        await update.message.reply_text(
            "❌ **ACCESS DENIED**\n\nThis command is restricted to administrators only.\n\n👨‍💻 **Developer:** @CRAXOP",
            parse_mode='Markdown'
        )
        return
    
    users = subscription_manager.get_all_users()
    active_users = [u for u in users if u["active"]]
    expired_users = [u for u in users if not u["active"]]
    
    admin_message = f"""
🔐 **CRAX KEYWORD GENERATOR - ADMIN PANEL**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👑 **ADMIN DASHBOARD**

📊 **USER STATISTICS:**
• Active Users: {len(active_users)}
• Expired Users: {len(expired_users)}
• Total Users: {len(users)}

🔧 **ADMIN COMMANDS:**

🔑 `/genkey <days>` - Generate access key
   └ Example: `/genkey 30`

📢 `/cast <message>` - Broadcast to all users
   └ Example: `/cast Hello everyone!`

🏓 `/ping` - Check bot status

📊 `/stats` - Detailed bot statistics

👥 `/users` - View all users

🧹 `/cleanup` - Remove expired users

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
🚀 **CRAX Admin System v2.0**
    """
    
    await update.message.reply_text(admin_message, parse_mode='Markdown')

async def genkey_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """🔑 Generate access key (Admin only)"""
    if update.effective_user.id != ADMIN_ID:
        await update.message.reply_text(
            "❌ **ACCESS DENIED**\n\nThis command is restricted to administrators only.\n\n👨‍💻 **Developer:** @CRAXOP",
            parse_mode='Markdown'
        )
        return
    
    if not context.args or not context.args[0].isdigit():
        await update.message.reply_text(
            f"""
❌ **INVALID FORMAT**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔥 **CORRECT USAGE:**
`/genkey <days>`

💡 **EXAMPLES:**
• `/genkey 30` - 30 days access
• `/genkey 90` - 90 days access
• `/genkey 365` - 1 year access

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
            """,
            parse_mode='Markdown'
        )
        return
    
    days = int(context.args[0])
    
    if days < 1 or days > 3650:  # Max 10 years
        await update.message.reply_text(
            "❌ **INVALID DAYS**\n\nDays must be between 1 and 3650 (10 years)\n\n👨‍💻 **Developer:** @CRAXOP",
            parse_mode='Markdown'
        )
        return
    
    key = subscription_manager.generate_key(days)
    
    success_message = f"""
✅ **ACCESS KEY GENERATED!**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔑 **KEY:** `{key}`
⏰ **VALIDITY:** {days} days
📅 **GENERATED:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

💡 **INSTRUCTIONS FOR USER:**
Send this key to the user and ask them to use:
`/redeem {key}`

⚠️ **IMPORTANT:**
• Key can only be redeemed once
• User must not have existing subscription
• Key expires when redeemed + {days} days

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
    """
    
    await update.message.reply_text(success_message, parse_mode='Markdown')

async def cast_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """📢 Broadcast message to all users (Admin only)"""
    if update.effective_user.id != ADMIN_ID:
        await update.message.reply_text(
            "❌ **ACCESS DENIED**\n\nThis command is restricted to administrators only.\n\n👨‍💻 **Developer:** @CRAXOP",
            parse_mode='Markdown'
        )
        return
    
    if not context.args:
        await update.message.reply_text(
            f"""
❌ **NO MESSAGE PROVIDED**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔥 **CORRECT USAGE:**
`/cast <message>`

💡 **EXAMPLE:**
`/cast 🔥 New features added! Check them out!`

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
            """,
            parse_mode='Markdown'
        )
        return
    
    message = ' '.join(context.args)
    users = subscription_manager.get_all_users()
    active_users = [u for u in users if u["active"]]
    
    broadcast_message = f"""
📢 **BROADCAST FROM ADMIN**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{message}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
    """
    
    sent_count = 0
    failed_count = 0
    
    for user in active_users:
        try:
            await context.bot.send_message(
                chat_id=user["user_id"],
                text=broadcast_message,
                parse_mode='Markdown'
            )
            sent_count += 1
        except:
            failed_count += 1
    
    result_message = f"""
✅ **BROADCAST COMPLETED!**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 **RESULTS:**
• Messages Sent: {sent_count}
• Failed: {failed_count}
• Total Active Users: {len(active_users)}

📝 **MESSAGE:**
{message}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
    """
    
    await update.message.reply_text(result_message, parse_mode='Markdown')

async def ping_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """🏓 Check bot status (Admin only)"""
    if update.effective_user.id != ADMIN_ID:
        await update.message.reply_text(
            "❌ **ACCESS DENIED**\n\nThis command is restricted to administrators only.\n\n👨‍💻 **Developer:** @CRAXOP",
            parse_mode='Markdown'
        )
        return
    
    start_time = time.time()
    
    ping_message = f"""
🏓 **CRAX BOT STATUS CHECK**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✅ **STATUS:** 200 OK
⚡ **RESPONSE TIME:** {(time.time() - start_time) * 1000:.2f}ms
🕐 **TIMESTAMP:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
🤖 **BOT:** Online and Operational
🔥 **SYSTEM:** All Services Running

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
    """
    
    await update.message.reply_text(ping_message, parse_mode='Markdown')

async def users_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """👥 View all users (Admin only)"""
    if update.effective_user.id != ADMIN_ID:
        await update.message.reply_text(
            "❌ **ACCESS DENIED**\n\nThis command is restricted to administrators only.\n\n👨‍💻 **Developer:** @CRAXOP",
            parse_mode='Markdown'
        )
        return
    
    users = subscription_manager.get_all_users()
    active_users = [u for u in users if u["active"]]
    expired_users = [u for u in users if not u["active"]]
    
    users_message = f"""
👥 **USER MANAGEMENT PANEL**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 **STATISTICS:**
• Total Users: {len(users)}
• Active Users: {len(active_users)}
• Expired Users: {len(expired_users)}

✅ **ACTIVE USERS:**
"""
    
    for user in active_users[:10]:  # Show first 10
        days_left = (user["expiry_date"] - datetime.now()).days
        users_message += f"• {user['username']} (ID: {user['user_id']}) - {days_left} days left\n"
    
    if len(active_users) > 10:
        users_message += f"... and {len(active_users) - 10} more\n"
    
    if expired_users:
        users_message += f"\n❌ **EXPIRED USERS:** {len(expired_users)}\n"
    
    users_message += f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
    """
    
    await update.message.reply_text(users_message, parse_mode='Markdown')

async def cleanup_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """🧹 Cleanup expired users (Admin only)"""
    if update.effective_user.id != ADMIN_ID:
        await update.message.reply_text(
            "❌ **ACCESS DENIED**\n\nThis command is restricted to administrators only.\n\n👨‍💻 **Developer:** @CRAXOP",
            parse_mode='Markdown'
        )
        return
    
    users_before = subscription_manager.get_all_users()
    expired_before = [u for u in users_before if not u["active"]]
    
    subscription_manager.cleanup_expired_users()
    
    users_after = subscription_manager.get_all_users()
    
    cleanup_message = f"""
🧹 **CLEANUP COMPLETED!**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 **RESULTS:**
• Users Before: {len(users_before)}
• Users After: {len(users_after)}
• Expired Users Removed: {len(expired_before)}

✅ **STATUS:** Database cleaned successfully

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
    """
    
    await update.message.reply_text(cleanup_message, parse_mode='Markdown')

async def redeem_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """🔑 Redeem access key"""
    user = update.effective_user
    
    if not context.args:
        await update.message.reply_text(
            f"""
❌ **NO KEY PROVIDED**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔥 **CORRECT USAGE:**
`/redeem <your-key>`

💡 **EXAMPLE:**
`/redeem CRAX-KEYWORD-123456`

🔑 **GET A KEY:**
Contact @CRAXOP to purchase access

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
            """,
            parse_mode='Markdown'
        )
        return
    
    key = context.args[0].upper()
    username = f"@{user.username}" if user.username else user.first_name
    
    result = subscription_manager.redeem_key(key, user.id, username)
    
    if result["success"]:
        success_message = f"""
🎉 **KEY REDEEMED SUCCESSFULLY!**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✅ **WELCOME TO CRAX KEYWORD GENERATOR!**

🔑 **KEY:** `{key}`
👤 **USER:** {username}
📅 **ACCESS UNTIL:** {result["expiry_date"]}

🔥 **YOU CAN NOW:**
• Generate unlimited keywords
• Use all premium features
• Access advanced Keywords

💡 **GET STARTED:**
Type `/keywords <topic> <quantity>` to begin!

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
🚀 **Welcome to the premium experience!**
        """
        await update.message.reply_text(success_message, parse_mode='Markdown')
    else:
        error_message = f"""
❌ **KEY REDEMPTION FAILED**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⚠️ **ERROR:** {result["message"]}

💡 **POSSIBLE REASONS:**
• Key is invalid or expired
• Key already redeemed by someone else
• You already have active subscription

🔑 **NEED HELP?**
Contact @CRAXOP for support

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
        """
        await update.message.reply_text(error_message, parse_mode='Markdown')

async def stats_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """📊 Show bot statistics (Admin only)"""
    if update.effective_user.id != ADMIN_ID:
        await update.message.reply_text(
            "❌ **ACCESS DENIED**\n\nThis command is restricted to administrators only.\n\n👨‍💻 **Developer:** @CRAXOP",
            parse_mode='Markdown'
        )
        return
    
    stats_message = f"""
📊 **CRAX KEYWORD GENERATOR - ADMIN PANEL**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🤖 **BOT STATUS:** ✅ ACTIVE
⏰ **UPTIME:** Running Smoothly
👑 **ADMIN ID:** `{ADMIN_ID}`
🔥 **VERSION:** 2.0 Professional

🎯 **AVAILABLE COMMANDS:**
• `/start` - Welcome screen
• `/cmd` - Command center
• `/keywords` - Keyword generation
• `/stats` - This admin panel

⚡ **SYSTEM FEATURES:**
✅ Advanced keyword generation
✅ Professional pdf file output
✅ Semantic analysis engine
✅ Multi-API integration
✅ Error handling & logging
✅ Professional UI/UX

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
🚀 **Powered by CRAX Technologies**
    """
    
    await update.message.reply_text(stats_message, parse_mode='Markdown')

async def handle_callback_query(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle inline keyboard callbacks"""
    query = update.callback_query
    await query.answer()
    
    if query.data == "show_commands":
        # Show the same content as /cmd command
        cmd_message = f"""
🎯 **CRAX KEYWORD GENERATOR - COMMAND CENTER**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔥 **AVAILABLE COMMANDS:**

🏠 `/start` - **HOME PAGE**
   └ Return to main welcome screen

🎯 `/keywords <topic> <quantity>` - **GENERATE KEYWORDS**
   └ Example: `/keywords credit card 500`
   └ Get Crax-powered keyword suggestions
   └ ⚡ UNLIMITED KEYWORDS! ♾️

📋 `/cmd` - **COMMAND CENTER**
   └ View this command list

📊 `/stats` - **BOT STATISTICS** (Admin Only)
   └ View bot performance metrics

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💡 **HOW TO USE:**
1️⃣ Type `/keywords` followed by your topic
2️⃣ Wait for processing ⚡
3️⃣ Receive professional TXT file 📄
4️⃣ Download and use for your projects! 🚀

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔥 **EXAMPLE USAGE:**
• `/keywords digital marketing 500`
• `/keywords cryptocurrency 1000`
• `/keywords web development 300`
• `/keywords artificial intelligence 750`

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
⚡ **Powered by Advanced System & API'S**
        """
        
        keyboard = [
            [InlineKeyboardButton("🔥 TRY NOW", callback_data="try_keywords")],
            [InlineKeyboardButton("🏠 HOME", callback_data="go_home")]
        ]
        reply_markup = InlineKeyboardMarkup(keyboard)
        
        await query.edit_message_text(
            cmd_message,
            parse_mode='Markdown',
            reply_markup=reply_markup
        )
    elif query.data == "try_keywords":
        await query.edit_message_text(
            "🔥 **READY TO GENERATE KEYWORDS?**\n\nType: `/keywords <topic> <quantity>`\n\nExample: `/keywords artificial intelligence 500`\n\n⚡ **UNLIMITED POWER!** ♾️\n\n👨‍💻 **Developer:** @CRAXOP",
            parse_mode='Markdown'
        )
    elif query.data == "go_home":
        # Recreate the start message
        user = query.from_user
        username = f"@{user.username}" if user.username else user.first_name
        
        welcome_message = f"""
🔥 **WELCOME TO CRAX KEYWORD GENERATOR** 🔥

Hello {username}! 👋

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🚀 **PROFESSIONAL KEYWORD TOOL**

✨ Generate **HIGH-QUALITY** keywords for any topic
🎯 **ADVANCED** semantic analysis
⚡ **INSTANT** results in TXT format
🔥 **PROFESSIONAL** grade output

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎪 **Ready to see the MAGIC?**
Type `/cmd` to explore all features!

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
🏷️ **Version:** 2.0 Pro
        """
        
        keyboard = [
            [InlineKeyboardButton("🎯 VIEW COMMANDS", callback_data="show_commands")],
            [InlineKeyboardButton("👨‍💻 CONTACT DEVELOPER", url="https://t.me/CRAXOP")]
        ]
        reply_markup = InlineKeyboardMarkup(keyboard)
        
        await query.edit_message_text(
            welcome_message,
            parse_mode='Markdown',
            reply_markup=reply_markup
        )

async def handle_unknown_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle unknown commands and messages"""
    unknown_message = f"""
❓ **UNKNOWN COMMAND**

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔥 **AVAILABLE COMMANDS:**
• `/start` - Home page
• `/cmd` - View all commands  
• `/keywords <topic> <quantity>` - Generate keywords

💡 **EXAMPLE:**
`/keywords credit card 500`

⚡ **UNLIMITED POWER!** ♾️

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍💻 **Developer:** @CRAXOP
    """
    
    await update.message.reply_text(unknown_message, parse_mode='Markdown')

async def error_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle errors"""
    logger.error(f"Update {update} caused error {context.error}")

# ═══════════════════════════════════════════════════════════════════════════════
# 🚀 MAIN APPLICATION ENTRY POINT
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    """🔥 Launch the CRAX Keyword Generator Bot"""
    
    # Validate configuration
    if BOT_TOKEN == "YOUR_BOT_TOKEN_HERE":
        print("❌ ERROR: Please set your BOT_TOKEN!")
        print("🔧 Get your token from @BotFather on Telegram")
        return
    
    if ADMIN_ID == 123456789:
        print("⚠️  WARNING: Please set your ADMIN_ID!")
        print("🔧 Get your user ID from @userinfobot")
    
    # Create application
    application = Application.builder().token(BOT_TOKEN).build()
    
    # Add command handlers
    application.add_handler(CommandHandler("start", start_command))
    application.add_handler(CommandHandler("cmd", cmd_command))
    application.add_handler(CommandHandler("keywords", keywords_command))
    application.add_handler(CommandHandler("redeem", redeem_command))
    
    # Admin commands
    application.add_handler(CommandHandler("admin", admin_command))
    application.add_handler(CommandHandler("genkey", genkey_command))
    application.add_handler(CommandHandler("cast", cast_command))
    application.add_handler(CommandHandler("ping", ping_command))
    application.add_handler(CommandHandler("users", users_command))
    application.add_handler(CommandHandler("cleanup", cleanup_command))
    application.add_handler(CommandHandler("stats", stats_command))
    
    # Add callback query handler for inline buttons
    application.add_handler(CallbackQueryHandler(handle_callback_query))
    
    # Add message handler for unknown commands
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_unknown_command))
    
    # Add error handler
    application.add_error_handler(error_handler)
    
    # Launch bot
    print("🔥 CRAX KEYWORD GENERATOR BOT STARTING...")
    print(f"🤖 Bot Token: {BOT_TOKEN[:10]}...")
    print(f"👑 Admin ID: {ADMIN_ID}")
    print("✅ Bot is LIVE! Press Ctrl+C to stop.")
    print("👨‍💻 Developer: @CRAXOP")
    
    # Run the bot
    application.run_polling(allowed_updates=Update.ALL_TYPES)

if __name__ == "__main__":
    main()
